### ISSUE TITLE
Поменять кидаемый объект

### ISSUE THREAD

**Issue by facelessbody** [Disum/dsrep#1]
https://github.com/Disum/dsrep/blob/47094b2886c5534873b792519defcf682a318051/main.cpp#L29

Очень хорошо, осталось добавить немного смысла) когда словом это исключение, хорошо бы, чтобы была возможность получить более детальное описание ошибки. Посмотри в сторону std::invalid_argument("error details")

**Comment by facelessbody** [comment]
Собственно, я предлагаю бросать std::invalid_argument вместо нуля)

**Comment by Disum** [comment]
Сделано
